tasks:
  - before: |
      rm -rf $HOME/.cargo
      unset CARGO_HOME
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      echo 'export CARGO_HOME="$HOME/.cargo"' >> ~/.bashrc
      source ~/.bashrc
      ls -la > /tmp/dir
    init: |
      gp open hello-gear/src/lib.rs
      clear && printf '\e[3J' && history -c
      cd hello-gear && cargo build --release
vscode:
  extensions:
    - rust-lang.rust-analyzer
    - marp-team.marp-vscode
